name: raku-dan:jupyter -> DH

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/jupyter-weekly.yaml
  schedule:
      - cron: "56 3 * * 4"

jobs:
  build-pandas:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64,linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          tags: librasteve/raku-dan:jupyter
          push: true
          platforms: linux/arm64,linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
